import React from 'react';
import ReactPlayer from 'react-player';

export default class AboutComponent extends React.Component {
  render() {
    return (
      <span className="E-about-wrap ">
        <div className="E-about-content">
          <div id="About">
            <div id="Group_5">
              <div id="HAVE">
                <span>HAVE</span>
              </div>
              <div id="FUN_">
                <span>FUN!</span>
              </div>
              <div id="ELEMENTS">
                <span>ELEMENTS</span>
              </div>
            </div>
            <div id="Entropy_is_a_interactive_specu">
              <span>Entropy is a interactive speculative history sandbox assisted by machine learning. The interface allows players to travel through time across a constantly updating database of major events throughout human history and to make choices that affect the timeline. Assisted with an AI capable of generating advanced simulations, the player gets to create and explore alternative timelines of history.</span>
            </div>
            <div id="Group_4">
              <svg class="Rectangle_30">
                <linearGradient spreadMethod="pad" id="LinearGradientFill1" x1="0.5" x2="0.5" y1="0" y2="1">
                  <stop offset="0" stop-color="#fff" stop-opacity="1"></stop>
                  <stop offset="0.1823" stop-color="#f0f0f0" stop-opacity="1"></stop>
                  <stop offset="0.8227" stop-color="#000" stop-opacity="1"></stop>
                  <stop offset="1" stop-color="#000" stop-opacity="1"></stop>
                </linearGradient>
                <rect fill="url(#LinearGradientFill1)" id="Rectangle_30" rx="0" ry="0" x="0" y="0" width="1918" height="1080">
                </rect>
              </svg>
              <div id="ENTROPY_">
                <span>ENTROPY?</span>
              </div>
              <div id="WHAT">
                <span>WHAT</span>
              </div>
              <div id="IS">
                <span>IS</span>
              </div>
            </div>
            <div id="en_tro_py___entr_p____the_traj">
              <span>en·tro·py /ˈentrəpē/: the trajectory of decline into disorder.</span>
            </div>
            <div id="Group_1">
              <svg class="Rectangle_3">
                <rect fill="rgba(255,255,255,1)" id="Rectangle_3" rx="0" ry="0" x="0" y="0" width="1226" height="690">
                </rect>
              </svg>
            </div>
            <div id="Video">
              <span>
                
              </span>
            </div>
            <svg class="Rectangle_24">
              <rect fill="rgba(255,255,255,1)" id="Rectangle_24" rx="199" ry="199" x="0" y="0" width="1226" height="398">
              </rect>
            </svg>
            <div id="Timeline__">
              <span>Timeline<br />-</span>
            </div>
            <div id="The_timeline_begins_at_the_daw">
              <span>The timeline begins at the dawn of the human civilization on Earth and proceeds through a progression of historical events. As the player, you can chose whether to allow major events <br />to happen or not. Rejecting an event will allow you to write new events with the help of AI, creating new alternate timelines of history. You can also explore timelines created by others.</span>
            </div>
            <div class="Rectangle_43">
              <ReactPlayer
                      className='E-react-player react-player'
                      url='https://vimeo.com/533029322'
                      height="100"
                      playing={true}
                      loop={true}
                      muted={true}
              />
              <rect fill="rgba(0,0,0,1)" id="Rectangle_43" rx="0" ry="0" x="0" y="0" width="398" height="398">
              </rect>
            </div>
            <div id="Group_30">
              <svg class="Rectangle_47">
                <rect fill="rgba(0,0,0,1)" id="Rectangle_47" rx="199" ry="199" x="0" y="0" width="1226" height="398">
                </rect>
              </svg>
              <div id="Viewport__">
                <span>Viewport<br />-</span>
              </div>
              <div id="The_viewport_on_the_right_hand">
                <span>The viewport on the right hand side displays a scene from the event. These scenes are generated by the AI through input from the players and a growing database of historical footage.</span>
              </div>
              <svg class="Rectangle_52">
                <rect fill="rgba(255,255,255,1)" id="Rectangle_52" rx="0" ry="0" x="0" y="0" width="398" height="398">
                </rect>
              </svg>
            </div>
            <div id="Group_33">
              <div id="Group_32">
                <svg class="Rectangle_44">
                  <rect fill="rgba(255,255,255,1)" id="Rectangle_44" rx="199" ry="199" x="0" y="0" width="1226" height="398">
                  </rect>
                </svg>
                <div id="Group_31">
                  <div id="Badges__">
                    <span>Badges<br />-</span>
                  </div>
                  <div id="Badges_are_achieved_after_a_ma">
                    <span>Badges are achieved after a major milestone in human history is achieved. Badges are divided into 5 categories: Era, Civics, Culture, Technology and Ecology. They are inputed into the AI to help new generate events. Players can create new events accordingly to the current badges</span>
                  </div>
                </div>
              </div>
              <svg class="Rectangle_46">
                <rect fill="rgba(0,0,0,1)" id="Rectangle_46" rx="199" ry="199" x="0" y="0" width="398" height="398">
                </rect>
              </svg>
            </div>
          </div>
        </div>
      </span>)
  }
}
